### PR TITLE
Use PATH instead of hardcoded sysctl location

### PR DESCRIPTION
**Pull request by jvehent**
A simple patch to fix an issue running on centos.

### CODE REVIEW

**Comment by benjamink** [comment]
Any chance of this being merged soon?

**Comment by thias** [comment]
Out of curiosity, which CentOS release? I've never had any issues with RHEL 6 and RHEL 7.

**Comment by benjamink** [comment]
Regardless of @jvehent's CentOS version, his fix seems more appropriate than how it's currently written.

**Comment by thias** [comment]
@benjamink : It's curiosity :-) Have you also encountered the issue? If so, on which distribution+release?

**Comment by benjamink** [comment]
I think I did, but it's been awhile since I looked.

**Pull request merged**
