### PR TITLE
Fix spaces in output of sysctl -n <key>

### PR DESCRIPTION
**Pull request by juliengk**

### CODE REVIEW

**Comment by thias** [comment]
I think I see what you're doing here, but I also think that it fixes some cases **and breaks** others. See #40 for some details. Basically, we would need to mangle both the value we are trying to set/compare **and** the value the system reports if we want to avoid breakage.

This is what my module was doing in the past, but it also had its own downsides : The code is more complex and more fragile, and AFAICT some sysctl values could contain multiple spaces on purpose (such as kernel.core_pattern), though in practice it might not be relevant...

For me it makes no doubt that the proper solution is to make sure the values being set are exactly the same as the ones sysctl reports, this means using tabs as-is. This is up to the users of the module. The real problem is that people have been used to setting mangled values, such as grouping kernel.sem with spaces instead of tabs...

Would a clear mention of this in the README be enough, perhaps?

**Comment by juliengk** [comment]
\s includes [ \t\r\n\f]. So it should not break others.

yes you are right that both value return by the command and the one provided should be mangled. I started to look at that and i haven't finished.

**Comment by juliengk** [comment]
i have added parsing of the value provided. Let me know what you think.

**Comment by juliengk** [comment]
@thias que penses-tu du dernier changement?

**Comment by juliengk** [comment]
@thias what do you think?

**Comment by dantremblay** [comment]
@thias please let us know what you think of this change.  We could use this in our environment.  Thanks!

**Comment by nbentoumi** [comment]
:+1:

**Comment by pckls** [comment]
@juliengk I was about to hack something up to solve this very issue.

One thing I've noticed from testing in a shell is that there is a difference between single vs double quotes for those sed statements - http://stackoverflow.com/questions/6697753/difference-between-single-and-double-quotes-in-bash

When I use `/sbin/sysctl -n net.ipv4.tcp_wmem | sed -r 's/\\s+/ /g'` the tabs are still there however `/sbin/sysctl -n net.ipv4.tcp_wmem | sed -r "s/\\s+/ /g"` works, I assume because it's not interpreting the backslash as a literal?

**Comment by pckls** [comment]
I've decided to just pass in my Hiera variables with the tabs because I think it's the cleanest solution.

**Comment by benohara** [comment]
I see this after an upgrade...this looks to fix it for me

    -          unless  => "/usr/bin/test \"$(/sbin/sysctl -n ${qtitle})\" = ${qvalue}",
    +          unless  => "/usr/bin/test \"$(/sbin/sysctl -n ${qtitle} | /bin/sed 's/\t/ /g')\" = ${qvalue}",

**Comment by bschonec** [comment]
I can confirm that @benohara code change made {my} runs idempotent.

**Pull request closed without merging**
